//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavBar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.NavBar", typeof(NavBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecté le :.
        /// </summary>
        public static string Date_Connected {
            get {
                return ResourceManager.GetString("Date_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Lang_French {
            get {
                return ResourceManager.GetString("Lang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer mon compte.
        /// </summary>
        public static string Manage_Account {
            get {
                return ResourceManager.GetString("Manage_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg_AccessDenied.
        /// </summary>
        public static string Msg_AccessDenied {
            get {
                return ResourceManager.GetString("Msg_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg_AuthRequired.
        /// </summary>
        public static string Msg_AuthRequired {
            get {
                return ResourceManager.GetString("Msg_AuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_CdSet.
        /// </summary>
        public static string Nav_CdSet {
            get {
                return ResourceManager.GetString("Nav_CdSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_ClientList.
        /// </summary>
        public static string Nav_ClientList {
            get {
                return ResourceManager.GetString("Nav_ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Clients.
        /// </summary>
        public static string Nav_Clients {
            get {
                return ResourceManager.GetString("Nav_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_DRDFiles.
        /// </summary>
        public static string Nav_DRDFiles {
            get {
                return ResourceManager.GetString("Nav_DRDFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav Usager.
        /// </summary>
        public static string Nav_ManageUsers {
            get {
                return ResourceManager.GetString("Nav_ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Messages.
        /// </summary>
        public static string Nav_Messages {
            get {
                return ResourceManager.GetString("Nav_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Pilotage.
        /// </summary>
        public static string Nav_Pilotage {
            get {
                return ResourceManager.GetString("Nav_Pilotage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav register.
        /// </summary>
        public static string Nav_Register {
            get {
                return ResourceManager.GetString("Nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Reports.
        /// </summary>
        public static string Nav_Reports {
            get {
                return ResourceManager.GetString("Nav_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sécurité.
        /// </summary>
        public static string Nav_Security {
            get {
                return ResourceManager.GetString("Nav_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNI Institution Financière Tous droits réservés.
        /// </summary>
        public static string Trade_Mark {
            get {
                return ResourceManager.GetString("Trade_Mark", resourceCulture);
            }
        }
    }
}
