//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SideBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SideBar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.SideBar", typeof(SideBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients_Client {
            get {
                return ResourceManager.GetString("Clients_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails client.
        /// </summary>
        public static string Clients_ClientDetails {
            get {
                return ResourceManager.GetString("Clients_ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individu.
        /// </summary>
        public static string Clients_Individual {
            get {
                return ResourceManager.GetString("Clients_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des clients.
        /// </summary>
        public static string Clients_Section {
            get {
                return ResourceManager.GetString("Clients_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CdSet.
        /// </summary>
        public static string Pilotage_CdSet {
            get {
                return ResourceManager.GetString("Pilotage_CdSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions financières.
        /// </summary>
        public static string Pilotage_FinancialInstitution {
            get {
                return ResourceManager.GetString("Pilotage_FinancialInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilotage.
        /// </summary>
        public static string Pilotage_Section {
            get {
                return ResourceManager.GetString("Pilotage_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages Web.
        /// </summary>
        public static string Pilotage_WebMessage {
            get {
                return ResourceManager.GetString("Pilotage_WebMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production de rapports.
        /// </summary>
        public static string Reports_Production {
            get {
                return ResourceManager.GetString("Reports_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string Reports_Section {
            get {
                return ResourceManager.GetString("Reports_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string Security_Register {
            get {
                return ResourceManager.GetString("Security_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôles.
        /// </summary>
        public static string Security_Roles {
            get {
                return ResourceManager.GetString("Security_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de la sécurité.
        /// </summary>
        public static string Security_Section {
            get {
                return ResourceManager.GetString("Security_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string Security_Users {
            get {
                return ResourceManager.GetString("Security_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables de base de données.
        /// </summary>
        public static string Stats_DatabaseTable {
            get {
                return ResourceManager.GetString("Stats_DatabaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string Stats_Section {
            get {
                return ResourceManager.GetString("Stats_Section", resourceCulture);
            }
        }
    }
}
