//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources.Informations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Informations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Informations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.Informations.Informations", typeof(Informations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une famille existante ou laissez ce champ vide pour créer une nouvelle famille..
        /// </summary>
        public static string FamilySelection_Help {
            get {
                return ResourceManager.GetString("FamilySelection_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès sécurisé à votre espace client DRD.
        /// </summary>
        public static string Header_Uni_Subtitle {
            get {
                return ResourceManager.GetString("Header_Uni_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNI Institution Financière.
        /// </summary>
        public static string Header_Uni_Title {
            get {
                return ResourceManager.GetString("Header_Uni_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dépôt direct : élimine l&apos;émission de chèques aux individus.
        /// </summary>
        public static string Info_Avantages_P1 {
            get {
                return ResourceManager.GetString("Info_Avantages_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait direct : élimine la réception de paiements par chèques.
        /// </summary>
        public static string Info_Avantages_P2 {
            get {
                return ResourceManager.GetString("Info_Avantages_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Économies : réduction des coûts d&apos;impression.
        /// </summary>
        public static string Info_Avantages_P3 {
            get {
                return ResourceManager.GetString("Info_Avantages_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avantages : épargnez temps et argent.
        /// </summary>
        public static string Info_Avantages_Title {
            get {
                return ResourceManager.GetString("Info_Avantages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce service permet à toute entreprise d&apos;expédier des dépôts ou faire des retraits à toute compagnie ou individu de façon simple et pratique..
        /// </summary>
        public static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solution idéale pour vos dépôts et retraits !.
        /// </summary>
        public static string Info_Solution_Ideal {
            get {
                return ResourceManager.GetString("Info_Solution_Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÉPÔTS / RETRAITS DIRECTS.
        /// </summary>
        public static string Info_Title {
            get {
                return ResourceManager.GetString("Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenu {0}.
        /// </summary>
        public static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
    }
}
