//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources.ToastrMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CdSetToastr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CdSetToastr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.ToastrMessages.CdSetToastr", typeof(CdSetToastr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’élément CdSet « {0}  - {1} » n&apos;a pas été trouvé!.
        /// </summary>
        public static string CdSet_NotFound {
            get {
                return ResourceManager.GetString("CdSet_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la création CdSet {0} - {1}.
        /// </summary>
        public static string Create_Error {
            get {
                return ResourceManager.GetString("Create_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de désactiver la famille de codes « {0} »..
        /// </summary>
        public static string DeactivateFamily_Error {
            get {
                return ResourceManager.GetString("DeactivateFamily_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun code actif trouvé pour la famille « {0} »..
        /// </summary>
        public static string DeactivateFamily_NotFound {
            get {
                return ResourceManager.GetString("DeactivateFamily_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La famille de codes « {0} » a été désactivée avec succès..
        /// </summary>
        public static string DeactivateFamily_Success {
            get {
                return ResourceManager.GetString("DeactivateFamily_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la mise à jour CdSet {0} - {1}.
        /// </summary>
        public static string Edit_Error {
            get {
                return ResourceManager.GetString("Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de réactiver la famille de codes « {0} »..
        /// </summary>
        public static string ReactivateFamily_Error {
            get {
                return ResourceManager.GetString("ReactivateFamily_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun code inactif trouvé pour la famille « {0} »..
        /// </summary>
        public static string ReactivateFamily_NotFound {
            get {
                return ResourceManager.GetString("ReactivateFamily_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La famille de codes « {0} » a été réactivée avec succès..
        /// </summary>
        public static string ReactivateFamily_Success {
            get {
                return ResourceManager.GetString("ReactivateFamily_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’élément CdSet « {0}  - {1} » a été créé avec succès..
        /// </summary>
        public static string Success_EntityCreated {
            get {
                return ResourceManager.GetString("Success_EntityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’élément CdSet « {0} -{1} » a été désactivé avec succès..
        /// </summary>
        public static string Success_EntityDeactivate {
            get {
                return ResourceManager.GetString("Success_EntityDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’élément CdSet « {0} - {1} » a été supprimé avec succès..
        /// </summary>
        public static string Success_EntityDeleted {
            get {
                return ResourceManager.GetString("Success_EntityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’élément CdSet « {0} -{1} » a été mis à jour avec succès..
        /// </summary>
        public static string Success_EntityUpdated {
            get {
                return ResourceManager.GetString("Success_EntityUpdated", resourceCulture);
            }
        }
    }
}
