//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources.EntityTitles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CdSetTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CdSetTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.EntityTitles.CdSetTitle", typeof(CdSetTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouveau code.
        /// </summary>
        public static string CdSet_Create_Title {
            get {
                return ResourceManager.GetString("CdSet_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails du code {0}-{1}.
        /// </summary>
        public static string CdSet_Detail_Title {
            get {
                return ResourceManager.GetString("CdSet_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour  du Code Set {0} -{1} .
        /// </summary>
        public static string CdSet_Edit_Title {
            get {
                return ResourceManager.GetString("CdSet_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Set.
        /// </summary>
        public static string CdSet_EntityName {
            get {
                return ResourceManager.GetString("CdSet_EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille inactive.
        /// </summary>
        public static string CdSet_FamilyInactive_Badge {
            get {
                return ResourceManager.GetString("CdSet_FamilyInactive_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver la famille.
        /// </summary>
        public static string DeactivateFamily_Button {
            get {
                return ResourceManager.GetString("DeactivateFamily_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivation d’une famille de codes.
        /// </summary>
        public static string DeactivateFamily_Title {
            get {
                return ResourceManager.GetString("DeactivateFamily_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver tous les codes de cette famille.
        /// </summary>
        public static string DeactivateFamily_Tooltip {
            get {
                return ResourceManager.GetString("DeactivateFamily_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette famille est désactivée.
        /// </summary>
        public static string FamilyInactive_Tooltip {
            get {
                return ResourceManager.GetString("FamilyInactive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des Familles de code disponibles.
        /// </summary>
        public static string Field_TypeCode_List_Title {
            get {
                return ResourceManager.GetString("Field_TypeCode_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réactiver la famille.
        /// </summary>
        public static string ReactivateFamily_Button {
            get {
                return ResourceManager.GetString("ReactivateFamily_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réactivation d’une famille de codes.
        /// </summary>
        public static string ReactivateFamily_Title {
            get {
                return ResourceManager.GetString("ReactivateFamily_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réactiver tous les codes de cette famille.
        /// </summary>
        public static string ReactivateFamily_Tooltip {
            get {
                return ResourceManager.GetString("ReactivateFamily_Tooltip", resourceCulture);
            }
        }
    }
}
