//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources.LabelNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityLN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityLN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.LabelNames.EntityLN", typeof(EntityLN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code du type d’accès.
        /// </summary>
        public static string AccessType_AccessTypeCode {
            get {
                return ResourceManager.GetString("AccessType_AccessTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (EN).
        /// </summary>
        public static string AccessType_DescriptionEn {
            get {
                return ResourceManager.GetString("AccessType_DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (FR).
        /// </summary>
        public static string AccessType_DescriptionFr {
            get {
                return ResourceManager.GetString("AccessType_DescriptionFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string AccessType_Users {
            get {
                return ResourceManager.GetString("AccessType_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d’accès.
        /// </summary>
        public static string ApplicationUser_AccessType {
            get {
                return ResourceManager.GetString("ApplicationUser_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code du type d’accès.
        /// </summary>
        public static string ApplicationUser_AccessTypeCode {
            get {
                return ResourceManager.GetString("ApplicationUser_AccessTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string ApplicationUser_AddressLine {
            get {
                return ResourceManager.GetString("ApplicationUser_AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé par:.
        /// </summary>
        public static string ApplicationUser_CreatedBy {
            get {
                return ResourceManager.GetString("ApplicationUser_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé le:.
        /// </summary>
        public static string ApplicationUser_CreationDate {
            get {
                return ResourceManager.GetString("ApplicationUser_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimante par défaut.
        /// </summary>
        public static string ApplicationUser_DefaultPrinter {
            get {
                return ResourceManager.GetString("ApplicationUser_DefaultPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string ApplicationUser_FirstName {
            get {
                return ResourceManager.GetString("ApplicationUser_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité.
        /// </summary>
        public static string ApplicationUser_IsActive {
            get {
                return ResourceManager.GetString("ApplicationUser_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimante laser.
        /// </summary>
        public static string ApplicationUser_LaserPrinter {
            get {
                return ResourceManager.GetString("ApplicationUser_LaserPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        public static string ApplicationUser_LastName {
            get {
                return ResourceManager.GetString("ApplicationUser_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code du menu.
        /// </summary>
        public static string ApplicationUser_MenuCode {
            get {
                return ResourceManager.GetString("ApplicationUser_MenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié le:.
        /// </summary>
        public static string ApplicationUser_ModificationDate {
            get {
                return ResourceManager.GetString("ApplicationUser_ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        public static string ApplicationUser_PostalCode {
            get {
                return ResourceManager.GetString("ApplicationUser_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string ApplicationUser_Province {
            get {
                return ResourceManager.GetString("ApplicationUser_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code secteur.
        /// </summary>
        public static string ApplicationUser_SectorCode {
            get {
                return ResourceManager.GetString("ApplicationUser_SectorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié par:.
        /// </summary>
        public static string ApplicationUser_UpdatedBy {
            get {
                return ResourceManager.GetString("ApplicationUser_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droits d’accès.
        /// </summary>
        public static string ApplicationUser_ViewAccesses {
            get {
                return ResourceManager.GetString("ApplicationUser_ViewAccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se souvenir de moi.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
    }
}
