//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRD.Resources.MessagesMetier.CdSet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CdSetMM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CdSetMM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRD.Resources.MessagesMetier.CdSet.CdSetMM", typeof(CdSetMM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette opération enfreint une règle métier propre au module CdSet..
        /// </summary>
        public static string CdSetMM_BusinessRule_XYZ {
            get {
                return ResourceManager.GetString("CdSetMM_BusinessRule_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Code avec cette clé existe déjà..
        /// </summary>
        public static string CdSetMM_Error_Duplicate {
            get {
                return ResourceManager.GetString("CdSetMM_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer cet élément CdSet, car il est actuellement utilisé..
        /// </summary>
        public static string CdSetMM_Error_InUse {
            get {
                return ResourceManager.GetString("CdSetMM_Error_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ Code est requis..
        /// </summary>
        public static string CdSetMM_Validation_CodeRequired {
            get {
                return ResourceManager.GetString("CdSetMM_Validation_CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ TypeCode est requis..
        /// </summary>
        public static string CdSetMM_Validation_TypeCodeRequired {
            get {
                return ResourceManager.GetString("CdSetMM_Validation_TypeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir la Famille.
        /// </summary>
        public static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Cette action désactivera tous les codes de la famille « {0} ».
        ///Les codes ne seront plus disponibles à l’utilisation,
        ///mais l’historique sera conservé.
        ///
        ///Voulez-vous continuer ?
        ///.
        /// </summary>
        public static string DeactivateFamily_Confirm {
            get {
                return ResourceManager.GetString("DeactivateFamily_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Cette action réactivera tous les codes de la famille « {0} ».
        ///Les codes redeviendront disponibles à l’utilisation.
        ///
        ///Voulez-vous continuer ?
        ///.
        /// </summary>
        public static string ReactivateFamily_Confirm {
            get {
                return ResourceManager.GetString("ReactivateFamily_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce Champs est requis.
        /// </summary>
        public static string Validation_NewFamilyRequired {
            get {
                return ResourceManager.GetString("Validation_NewFamilyRequired", resourceCulture);
            }
        }
    }
}
